#!/bin/sh

site=Helsinki
# Raw data zips directory zips to process
export Poleno_hourly_zips=/path_to_Poleno_zips/PolenoZips${site}
# Scripts directory
export Poleno_scripts=$HOME/path_to_repo_files
# Outputs
export Poleno_output=$HOME/path_to_output_dir/${site}
# Logs
export Log_dir=$Poleno_output/Logs
# Time series output file
export Recognition_Results_file=${site}_Poleno_Recognition.csv

